# Generated by Django 4.2.2 on 2023-06-16 13:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("recipe", "0002_recipe_author_recipe_date_posted"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="date_posted",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
