# Generated by Django 4.2.2 on 2023-06-21 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipe", "0002_ingredient_picture_recipe_picture"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="slug",
            field=models.CharField(default="", max_length=128),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="name",
            field=models.CharField(max_length=128),
        ),
    ]
