# Generated by Django 4.2.2 on 2023-06-22 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipe", "0003_recipe_slug_alter_recipe_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="nb_persons",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
